#%RAML 0.8
title: Steroids Data
mediaType: application/json
baseUri: https://rest-api.appgyver.com/v1/

traits:
  - securedBySteroidsApiKey:
      headers:
        steroidsApiKey:
          type: string
          example: exampleapikey
          default: acf99f766abc3bd670c99da23e8a389b3be12d05f5870c8bd7d8b369cde4cdeb
        steroidsAppId:
          type: integer
          example: 1234
          default: 55376

schemas:
  - taxidata_collection: '{"$schema":"http://json-schema.org/schema","title":"taxidata collection","type":"object","properties":{"results":{"type":"array","items":{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical taxidata representation","properties":{"createdAt":{"type":"string"},"departAddress":{"type":"string"},"objectId":{"type":"string"},"remainingSeats":{"type":"integer"},"updatedAt":{"type":"string"}},"required":[]}}}}'
  - taxidata_member: '{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical taxidata representation","properties":{"createdAt":{"type":"string"},"departAddress":{"type":"string"},"objectId":{"type":"string"},"remainingSeats":{"type":"integer"},"updatedAt":{"type":"string"}},"required":[]}'
  - taxidatatwo_collection: '{"$schema":"http://json-schema.org/schema","title":"taxidatatwo collection","type":"object","properties":{"results":{"type":"array","items":{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical taxidatatwo representation","properties":{"createdAt":{"type":"string"},"departDate":{"type":"string"},"departTime":{"type":"string"},"deptAddr":{"type":"string"},"destAddr":{"type":"string"},"maxPassengers":{"type":"integer"},"notes":{"type":"string"},"objectId":{"type":"string"},"partyLeader":{"type":"string"},"passengerList":{"type":"array"},"remainingSeats":{"type":"integer"},"updatedAt":{"type":"string"}, "deptObj":{"type":"object"}, "destObj":{"type":"object"}},"required":[]}}}}'
  - taxidatatwo_member: '{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical taxidatatwo representation","properties":{"createdAt":{"type":"string"},"departDate":{"type":"string"},"departTime":{"type":"string"},"deptAddr":{"type":"string"},"destAddr":{"type":"string"},"maxPassengers":{"type":"integer"},"notes":{"type":"string"},"objectId":{"type":"string"},"partyLeader":{"type":"string"},"passengerList":{"type":"array"},"remainingSeats":{"type":"integer"},"updatedAt":{"type":"string"}, "deptObj":{"type":"object"}, "destObj":{"type":"object"}},"required":[]}'

resourceTypes:
  - dolan_db_collection:
      usage: This resourceType should be used for any collection of items
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "collection"
          }
        responses:
          200:
            description: |
              {
                "rootKey": "objects"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_collection # e.g cars
      post:
        description: |
          {
            "action": "create",
            "rootKey": "object"
          }
        body:
          application/json:
            schema: <<resourcePathName>>_member
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_member # e.g. car

  - dolan_db_member:
      usage: This resourceType should be used for any built.io item
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "find"
          }
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_member # e.g. car
      put:
        description: |
          {
            "action": "update",
            "rootKey": "object"
          }
        body:
          application/json:
            schema: <<resourcePathName>>_member
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_member
      delete:
        description: |
          {
            "action": "destroy"
          }
        responses:
          200:

  - parse_collection:
      usage: This resourceType should be used for any collection of items
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "collection"
          }
        responses:
          200:
            description: |
              {
                "rootKey": "results"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_collection # e.g cars
      post:
        description: |
          {
            "action": "create"
          }
        body:
          application/json:
            schema: <<resourcePathName>>_member
        responses:
          200:
            body:
              application/json:
                schema: <<resourcePathName>>_member # e.g. car

  - parse_member:
      usage: This resourceType should be used for any parse item
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "find"
          }
        responses:
          200:
            body:
              application/json:
                schema: <<resourcePathName>>_member # e.g. car
      put:
        description: |
          {
            "action": "update"
          }
        body:
          application/json:
            schema: <<resourcePathName>>_member
        responses:
          200:
            body:
              application/json:
                schema: <<resourcePathName>>_member
      delete:
        description: |
          {
            "action": "destroy"
          }
        responses:
          200:


/taxidata:
  description: |
    {
      "resourceName": "taxidata",
      "identifierKey": "objectId"
    }
  type: parse_collection
  /{id}:
    type: parse_member

/taxidatatwo:
  description: |
    {
      "resourceName": "taxidatatwo",
      "identifierKey": "objectId"
    }
  type: parse_collection
  /{id}:
    type: parse_member


